.TH "Ecodena.Question.views" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Question.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommentForm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest\fP"
.br
.ti -1c
.RI "def \fBlistQuestions\fP"
.br
.ti -1c
.RI "def \fBviewQuestionByID\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Ecodena.Question.views.listQuestions (request)".PP
.nf
list all the questions with its title
parameter:request-->All the details associated with URL 
returns the question.html webpage and the list of questions.fi
.PP
 
.PP
Definition at line 19 of file views.py.
.SS "def Ecodena.Question.views.test (request)"
.PP
Definition at line 15 of file views.py.
.SS "def Ecodena.Question.views.viewQuestionByID (request, questionID)".PP
.nf
A question whose Id is passed as the parameter is displayed with the question title, question text, comment list
Parameter:request-->All the information of the form is stored in request
questionID-->the ID of question to be displayed
If the user is not authenticated then this returns an Http Response stating that the user is not logged in
If the user is authenticated and the form filled is valid then it returns the page with the question and other details.fi
.PP
 
.PP
Definition at line 26 of file views.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
