.TH "Ecodena.Compiler.dictionary" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Compiler.dictionary \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBcompilers\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "dictionary \fBEcodena::Compiler::dictionary.compilers\fP"\fBInitial value:\fP
.PP
.nf
1 {
2 
3 'C 1.1.1': Compiler.views.CCompile111,
4 'Java 1.1.1':Compiler.views.JavaCompile111,
5 
6 }
.fi
.PP
Definition at line 1 of file dictionary.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
