.TH "Ecodena::Comment::admin::CommentAdmin" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Comment::admin::CommentAdmin \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBlist_display\fP = ('commentID_f', 'commentText', 'userID', 'isReported_f', 'reportingUserID', 'questionID', 'timeStamp' )"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file admin.py.
.SH "Member Data Documentation"
.PP 
.SS "tuple \fBEcodena.Comment.admin.CommentAdmin.list_display\fP = ('commentID_f', 'commentText', 'userID', 'isReported_f', 'reportingUserID', 'questionID', 'timeStamp' )\fC [static]\fP"
.PP
Definition at line 5 of file admin.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
