.TH "Ecodena::Question::models::Type::Meta" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Question::models::Type::Meta \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBverbose_name\fP = 'type'"
.br
.ti -1c
.RI "string \fBverbose_name_plural\fP = 'types'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "string \fBEcodena.Question.models.Type.Meta.verbose_name\fP = 'type'\fC [static]\fP"
.PP
Definition at line 37 of file models.py.
.SS "string \fBEcodena.Question.models.Type.Meta.verbose_name_plural\fP = 'types'\fC [static]\fP"
.PP
Definition at line 38 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
