.TH "Ecodena::Attempt::views::SolutionForm" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Attempt::views::SolutionForm \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBtext\fP = forms.CharField(widget=forms.Textarea)"
.br
.ti -1c
.RI "tuple \fBversion\fP = forms.ChoiceField()"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
creates a form for pasting the solution of a question .fi
.PP
 
.PP
Definition at line 18 of file views.py.
.SH "Member Data Documentation"
.PP 
.SS "tuple \fBEcodena.Attempt.views.SolutionForm.text\fP = forms.CharField(widget=forms.Textarea)\fC [static]\fP"
.PP
Definition at line 20 of file views.py.
.SS "tuple \fBEcodena.Attempt.views.SolutionForm.version\fP = forms.ChoiceField()\fC [static]\fP"
.PP
Definition at line 21 of file views.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
