.TH "Ecodena::Question::admin::QuestionAdmin" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Question::admin::QuestionAdmin \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBinlines1\fP = [\fBTypeInline\fP]"
.br
.ti -1c
.RI "list \fBinlines2\fP = [\fBLevelInline\fP]"
.br
.ti -1c
.RI "tuple \fBlist_display\fP = ('questionID_f', 'questionTitle', 'level_f', 'type_f', 'timeLimit_f')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file admin.py.
.SH "Member Data Documentation"
.PP 
.SS "list \fBEcodena.Question.admin.QuestionAdmin.inlines1\fP = [\fBTypeInline\fP]\fC [static]\fP"
.PP
Definition at line 15 of file admin.py.
.SS "list \fBEcodena.Question.admin.QuestionAdmin.inlines2\fP = [\fBLevelInline\fP]\fC [static]\fP"
.PP
Definition at line 16 of file admin.py.
.SS "tuple \fBEcodena.Question.admin.QuestionAdmin.list_display\fP = ('questionID_f', 'questionTitle', 'level_f', 'type_f', 'timeLimit_f')\fC [static]\fP"
.PP
Definition at line 17 of file admin.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
