.TH "Ecodena::Comment::models::Comment::Meta" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Comment::models::Comment::Meta \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBverbose_name\fP = 'comment'"
.br
.ti -1c
.RI "string \fBverbose_name_plural\fP = 'comments'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "string \fBEcodena.Comment.models.Comment.Meta.verbose_name\fP = 'comment'\fC [static]\fP"
.PP
Definition at line 72 of file models.py.
.SS "string \fBEcodena.Comment.models.Comment.Meta.verbose_name_plural\fP = 'comments'\fC [static]\fP"
.PP
Definition at line 73 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
