.TH "Ecodena::Question::models::Question::Meta" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Question::models::Question::Meta \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBverbose_name\fP = 'question'"
.br
.ti -1c
.RI "string \fBverbose_name_plural\fP = 'questions'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "string \fBEcodena.Question.models.Question.Meta.verbose_name\fP = 'question'\fC [static]\fP"
.PP
Definition at line 96 of file models.py.
.SS "string \fBEcodena.Question.models.Question.Meta.verbose_name_plural\fP = 'questions'\fC [static]\fP"
.PP
Definition at line 97 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
