.TH "Ecodena.Attempt.models" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Attempt.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBErrorReport\fP"
.br
.ti -1c
.RI "class \fBAttempt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
This file creates the model Attempt.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
