.TH "Ecodena::User::models::Admin" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::User::models::Admin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits User.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBresolveQuery\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file models.py.
.SH "Member Function Documentation"
.PP 
.SS "def Ecodena.User.models.Admin.resolveQuery (self, queryID, solution)"
.PP
Definition at line 58 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
