.TH "/home/panx/ecodena/src/Ecodena/settings.py" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/panx/ecodena/src/Ecodena/settings.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBEcodena.settings\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBEcodena::settings.DEBUG\fP = True"
.br
.ti -1c
.RI "\fBEcodena::settings.TEMPLATE_DEBUG\fP = DEBUG"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.ADMINS\fP"
.br
.ti -1c
.RI "\fBEcodena::settings.MANAGERS\fP = ADMINS"
.br
.ti -1c
.RI "dictionary \fBEcodena::settings.DATABASES\fP"
.br
.ti -1c
.RI "string \fBEcodena::settings.TIME_ZONE\fP = 'America/Chicago'"
.br
.ti -1c
.RI "string \fBEcodena::settings.LANGUAGE_CODE\fP = 'en-us'"
.br
.ti -1c
.RI "int \fBEcodena::settings.SITE_ID\fP = 1"
.br
.ti -1c
.RI "\fBEcodena::settings.USE_I18N\fP = True"
.br
.ti -1c
.RI "\fBEcodena::settings.USE_L10N\fP = True"
.br
.ti -1c
.RI "string \fBEcodena::settings.MEDIA_ROOT\fP = ''"
.br
.ti -1c
.RI "string \fBEcodena::settings.MEDIA_URL\fP = ''"
.br
.ti -1c
.RI "string \fBEcodena::settings.STATIC_ROOT\fP = ''"
.br
.ti -1c
.RI "string \fBEcodena::settings.STATIC_URL\fP = '/static/'"
.br
.ti -1c
.RI "string \fBEcodena::settings.ADMIN_MEDIA_PREFIX\fP = '/static/admin/'"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.STATICFILES_DIRS\fP"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.STATICFILES_FINDERS\fP"
.br
.ti -1c
.RI "string \fBEcodena::settings.SECRET_KEY\fP = 'k!*n&!9$t9sp61=vq(%t^(k@yz7o^=*y=i2kmxtpi!4+88gyhl'"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.TEMPLATE_LOADERS\fP"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.MIDDLEWARE_CLASSES\fP"
.br
.ti -1c
.RI "string \fBEcodena::settings.ROOT_URLCONF\fP = 'Ecodena.urls'"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.TEMPLATE_DIRS\fP"
.br
.ti -1c
.RI "tuple \fBEcodena::settings.INSTALLED_APPS\fP"
.br
.ti -1c
.RI "string \fBEcodena::settings.AUTH_PROFILE_MODULE\fP = 'Ecodena.User.Profile'"
.br
.ti -1c
.RI "dictionary \fBEcodena::settings.LOGGING\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
