.TH "/home/panx/ecodena/src/Ecodena/User/tests.py" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/panx/ecodena/src/Ecodena/User/tests.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEcodena.User.tests.SimpleTest\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBEcodena.User.tests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
