.TH "Ecodena.Comment.models" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Comment.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComment\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
Its a models.py of Comment app, i.e. it will create a basic model for Comment app..fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
