.TH "Ecodena.Question.views" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Question.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommentForm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest\fP"
.br
.ti -1c
.RI "def \fBlistQuestions\fP"
.br
.ti -1c
.RI "def \fBviewQuestionByID\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Ecodena.Question.views.listQuestions (request)"
.PP
Definition at line 18 of file views.py.
.SS "def Ecodena.Question.views.test (request)"
.PP
Definition at line 14 of file views.py.
.SS "def Ecodena.Question.views.viewQuestionByID (request, questionID)"
.PP
Definition at line 22 of file views.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
