.TH "Ecodena.Question.tests" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Question.tests \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleTest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf

This file demonstrates writing tests using the unittest module. These will pass
when you run "manage.py test".

Replace this with more appropriate tests for your application.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
