.TH "Ecodena::User::admin::ProfileAdmin" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::User::admin::ProfileAdmin \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBlist_display\fP = ('profileID_f', 'dob_f', 'address_f', 'gender_f', 'userID_f', 'isProgrammer_f', 'isAdmin_f', 'numberOfAttempts_f')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file admin.py.
.SH "Member Data Documentation"
.PP 
.SS "tuple \fBEcodena.User.admin.ProfileAdmin.list_display\fP = ('profileID_f', 'dob_f', 'address_f', 'gender_f', 'userID_f', 'isProgrammer_f', 'isAdmin_f', 'numberOfAttempts_f')\fC [static]\fP"
.PP
Definition at line 10 of file admin.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
