.TH "Ecodena::Question::views::CommentForm" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Question::views::CommentForm \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBtext\fP = forms.CharField(widget=forms.Textarea)"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
Creates a form for writing a comment.fi
.PP
 
.PP
Definition at line 10 of file views.py.
.SH "Member Data Documentation"
.PP 
.SS "tuple \fBEcodena.Question.views.CommentForm.text\fP = forms.CharField(widget=forms.Textarea)\fC [static]\fP"
.PP
Definition at line 12 of file views.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
