.TH "Ecodena::Query::models::Query::Meta" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Query::models::Query::Meta \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBverbose_name\fP = 'query'"
.br
.ti -1c
.RI "string \fBverbose_name_plural\fP = 'queries'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "string \fBEcodena.Query.models.Query.Meta.verbose_name\fP = 'query'\fC [static]\fP"
.PP
Definition at line 74 of file models.py.
.SS "string \fBEcodena.Query.models.Query.Meta.verbose_name_plural\fP = 'queries'\fC [static]\fP"
.PP
Definition at line 75 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
