.TH "Ecodena::Question::models::TestCase::Meta" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Question::models::TestCase::Meta \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBverbose_name\fP = 'test case'"
.br
.ti -1c
.RI "string \fBverbose_name_plural\fP = 'test cases'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "string \fBEcodena.Question.models.TestCase.Meta.verbose_name\fP = 'test case'\fC [static]\fP"
.PP
Definition at line 143 of file models.py.
.SS "string \fBEcodena.Question.models.TestCase.Meta.verbose_name_plural\fP = 'test cases'\fC [static]\fP"
.PP
Definition at line 144 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
