.TH "Ecodena.Query.views" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Query.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQueryForm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpostQuery\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Ecodena.Query.views.postQuery (request)"
.PP
Definition at line 15 of file views.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
