.TH "Ecodena::Compiler::models::Language::Meta" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Compiler::models::Language::Meta \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBverbose_name\fP = 'language'"
.br
.ti -1c
.RI "string \fBverbose_name_plural\fP = 'languages'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "string \fBEcodena.Compiler.models.Language.Meta.verbose_name\fP = 'language'\fC [static]\fP"
.PP
Definition at line 19 of file models.py.
.SS "string \fBEcodena.Compiler.models.Language.Meta.verbose_name_plural\fP = 'languages'\fC [static]\fP"
.PP
Definition at line 20 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
