.TH "Ecodena.User.models" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.User.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProgrammer\fP"
.br
.ti -1c
.RI "class \fBProfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
Its a models.py of User app, i.e. it creates a basic model for User app..fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
