.TH "Ecodena.Query.models" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Query.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuery\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
Its a models.py of post Query, i.e. it creates a basic model for the post Query..fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
