.TH "Ecodena::Question::models::Type" 3 "Sun Mar 25 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena::Question::models::Type \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__unicode__\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBtypeID_f\fP = models.AutoField(primary_key=True)"
.br
.ti -1c
.RI "tuple \fBtypeName_f\fP = models.CharField('Type Name' , max_length = 30 , null = False)"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
Creates the entity Type which is a subclass of models.Model class.fi
.PP
 
.PP
Definition at line 31 of file models.py.
.SH "Member Function Documentation"
.PP 
.SS "def Ecodena.Question.models.Type.__unicode__ (self)"
.PP
Definition at line 40 of file models.py.
.SH "Member Data Documentation"
.PP 
.SS "tuple \fBEcodena.Question.models.Type.typeID_f\fP = models.AutoField(primary_key=True)\fC [static]\fP"
.PP
Definition at line 33 of file models.py.
.SS "tuple \fBEcodena.Question.models.Type.typeName_f\fP = models.CharField('Type Name' , max_length = 30 , null = False)\fC [static]\fP"
.PP
Definition at line 34 of file models.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
