.TH "Ecodena.Attempt.views" 3 "Tue Mar 20 2012" "Version 1.0" "Ecodena" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ecodena.Attempt.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSolutionForm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlistSolutions\fP"
.br
.ti -1c
.RI "def \fBviewSolution\fP"
.br
.ti -1c
.RI "def \fBsubmitSolution\fP"
.br
.ti -1c
.RI "def \fBcompileSolution\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Ecodena.Attempt.views.compileSolution (version, solution, question)"
.PP
Definition at line 65 of file views.py.
.SS "def Ecodena.Attempt.views.listSolutions (request)"
.PP
Definition at line 21 of file views.py.
.SS "def Ecodena.Attempt.views.submitSolution (request)"
.PP
Definition at line 40 of file views.py.
.SS "def Ecodena.Attempt.views.viewSolution (request, solutionID)"
.PP
Definition at line 28 of file views.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ecodena from the source code.
